# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/flosch/slideshow/models/slideshow/columns.yml

# Model Class name
modelClass: Flosch\Slideshow\Models\Slideshow